server:
  port: 8080
spring:
  application:
    name: gateway-service-zull

# 配置网关反向代理，例如访问/api-member/** 直接重定向到member-service服务,实现路由转发，隐藏服务的真实ip(服务都实在内网中)
zuul:
 routes:
   api-a:
     path: /api-member/**
     serviceId: member-service
   api-b:
     path: /api-order/**
     serviceId: order-service


#Eureka配置
eureka:
  client:
    service-url:
      defaultZone: http:// 172.19.182.141:8761/eureka/
  instance:
    #写定IP
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
